AdresseBelgique/Controllers/CodePostalController.cs
using AdresseBelgique.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AdresseBelgique.Controllers
{
    public class codePostalController : Controller
    {
        Query query = new Query();
        MyDbContext context = new MyDbContext();
        public string link = "http://geoservices.wallonie.be/geolocalisation/rest/getListeRuesByCp/";
        // GET: CodePostal
        public ActionResult Index(int? codepostal)
        {
            List<RueService> list = query.GetRues(link, codepostal.ToString());
            query.synchronisationRue(list);
            IEnumerable<Rue> rues = from rue in context.Rues.ToList()
                                    where rue.Cps == codepostal
                                    orderby rue.NomRue
                                    select rue;
            return View(rues);
        }
    }
}

AdresseBelgique/Controllers/addressController.cs
using AdresseBelgique.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AdresseBelgique.Controllers
{
    public class addressController : Controller
    {
        Query query = new Query();
        MyDbContext context = new MyDbContext();
        public string url = "http://geoservices.wallonie.be/geolocalisation/rest/getListeCommunes/";
        // GET: address
        public ActionResult Index()
        {
            List<CommuneService> list = query.GetCommunes(url);
            query.synchronisation(list);
            List<Commune> communes = context.Communes.ToList();
            return View(communes);
        }
    }
}

AdresseBelgique/Controllers/rueController.cs
using AdresseBelgique.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AdresseBelgique.Controllers
{
    public class rueController : Controller
    {
        Query query = new Query();
        MyDbContext context = new MyDbContext();
        public string link = "http://geoservices.wallonie.be/geolocalisation/rest/getListeRuesByCommune/";
        // GET: rue
        public ActionResult GetRues(string commune)
        {
            
            List<RueService> list = query.GetRues(link, commune);
            query.synchronisationRue(list);
            IEnumerable<Rue> rues = from rue in context.Rues.ToList()
                                    where rue.Commune == ( (commune != null) ? commune.ToUpper() : commune) 
                                    //orderby rue.NomRue
                                    select rue;
            //commune = Request.QueryString.Get("commune");

            return View(rues);
        }
    }
}

AdresseBelgique/Views/address/Index.cshtml
@model IEnumerable<AdresseBelgique.Models.Commune>

@{
    ViewBag.Title = "Index";
}

<h2>les communes</h2>
<div class="container ">
    <div class="panel panel-primary">
        <div class="panel-heading">la liste des communes </div>   
        <div class="panel-body">
            <div>
                <form method="post" asp-action="Search">
                    <div class="form-group">
                        <input type="text" name="keyword" id="myInput" placeholder="filtrer par mot clé.." class="form-control" />
                    </div>
                </form>
            </div>


            <table class="table table-hover table-condensed table-striped ">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.nom)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.cps)
                        </th>

                       
                    </tr>
                </thead>
                @foreach (var item in Model)
                {
            <tbody id="myTable">
                <tr>
                    <td>
                        @*@Html.DisplayFor(modelItem => item.nom)*@
                        @Html.ActionLink(item.nom,"GetRues","rue",new { commune = item.nom },null)     @*item.nom, "Details",new { item.nom }*@
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.cps)
                       @*@Html.ActionLink(item.cps, "Index", "codePostal", new { codepostal = item.cps },null)*@

                    </td>

                  
                </tr>
            </tbody>
                }

            </table>
        </div>
    </div>
    </div>
    