AdresseBelgique/Controllers/addressController.cs
using AdresseBelgique.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AdresseBelgique.Controllers
{
    public class addressController : Controller
    {
        Query query = new Query();
        MyDbContext context = new MyDbContext();
        public string url = "http://geoservices.wallonie.be/geolocalisation/rest/getListeCommunes/";
        // GET: address
        public ActionResult Index()
        {
            List<CommuneService> list = query.GetCommunes(url);
            query.synchronisation(list);
            List<Commune> communes = context.Communes.ToList();
            return View(communes);
        }
    }
}

AdresseBelgique/Controllers/localiteController.cs
using AdresseBelgique.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AdresseBelgique.Controllers
{
    public class localiteController : Controller
    {
        Query query = new Query();
        MyDbContext context = new MyDbContext();
        public string url = "http://geoservices.wallonie.be/geolocalisation/rest/getListeLocalites/";
        // GET: localite
        public ActionResult AllLocalites()
        {
            List<LocaliteService> list = query.GetLocalites(url);
            query.synchronisationLocalite(list);
            List<Localite> localites = context.Localites.ToList();
            return View(localites);
        }
    }
}

AdresseBelgique/Controllers/rueController.cs
using AdresseBelgique.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AdresseBelgique.Controllers
{
    public class rueController : Controller
    {
        Query query = new Query();
        MyDbContext context = new MyDbContext();
        public string link = "http://geoservices.wallonie.be/geolocalisation/rest/getListeRuesByCommune/";
        // GET: rue
        public ActionResult GetRues(string commune)
        {
            
            List<RueService> list = query.GetRues(link, commune);
            query.synchronisationRue(list);
            IEnumerable<Rue> rues = from rue in context.Rues.ToList()
                                    where rue.Commune == ( (commune != null) ? commune.ToUpper() : commune) 
                                    //orderby rue.NomRue
                                    select rue;
            //commune = Request.QueryString.Get("commune");

            return View(rues);
        }
    }
}

AdresseBelgique/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("les communes", "Index", "address", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("les localites", "AllLocalites", "localite", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("les rues", "GetRues", "rue", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("les rues par code postal", "Index", "CodePostal", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $("#myInput").on("keyup", function () {
                var value = $(this).val().toLowerCase();
                $("#myTable tr").filter(function () {
                    $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                });
            });

        });
    </script>
</body>
</html>